@baseurl = http://localhost:3000/api/urls


### Login
# @name LoginRequest
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "atul@example.com",
  "password": "password123"
}


### Create Short URL
POST {{baseurl}}/
Content-Type: application/json
Authorization: Bearer {{LoginRequest.response.body.accessToken}}

{
  "originalUrl": "https://www.youtube.com",
  "expiresAt": "2026-10-06T21:45:00"
}

### Get Short URL
GET http://localhost:3000/c
Authorization: Bearer {{LoginRequest.response.body.accessToken}}

### Update Short URL
PATCH {{baseurl}}/d
Content-Type: application/json
Authorization: Bearer {{LoginRequest.response.body.accessToken}}

{
  "originalUrl": "https://www.instagram.com"
}


### Delete Short URL
DELETE {{baseurl}}/d
Authorization: Bearer {{LoginRequest.response.body.accessToken}}
